--!strict

--[[
	A place to put named keybinds for consistent controls across the game
--]]

local Keybind = {
	GamepadPrimaryAction = Enum.KeyCode.ButtonA,
	GamepadSecondaryAction = Enum.KeyCode.ButtonB,
	GamepadSpecialAction = Enum.KeyCode.ButtonX,
	GamepadDefensiveAction = Enum.KeyCode.ButtonL1,
	KeyboardPrimaryAction = Enum.KeyCode.Z,
	KeyboardSecondaryAction = Enum.KeyCode.X,
	KeyboardSpecialAction = Enum.KeyCode.C,
	KeyboardDefensiveAction = Enum.KeyCode.V
}

return Keybind
